prepare:
  dataset_path: data/pakistan_house_prices.csv
  random_seed: 42

features:
  test_size: 0.2
  random_state: 42
  target_column: price
  categorical_features:
    - city
    - property_type
    - province_name
  numeric_features:
    - baths
    - bedrooms
    - Area_in_Marla

train:
  model_type: RandomForestRegressor
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42

evaluate:
  metrics:
    - rmse
    - mae
    - r2_score